### PR TITLE
Working in python 3.12

### LINKED ISSUE #372: AttributeError: 'FileFinder' object has no attribute 'find_module' when running on python 3.12
1. on an empty directory created `test_example.py`:
```python
from ward import test

@test("simple addition")
def _():
    assert 1 + 2 == 3
```
2. created a conda environment with python 3.12: `conda create --name ward-py312 python=3.12`
3. activated the conda environment with `conda activate ward-py312`
4. installed latest ward with `pip install ward` (got ward-0.67.2b0)
5. ran `ward` and got:
```bash
$ ward                                                                                                                                                       Traceback (most recent call last):
  File "/home/coutinho/miniconda/envs/ward-py312/bin/ward", line 8, in <module>
    sys.exit(run())
             ^^^^^
  File "/home/coutinho/miniconda/envs/ward-py312/lib/python3.12/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/coutinho/miniconda/envs/ward-py312/lib/python3.12/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/home/coutinho/miniconda/envs/ward-py312/lib/python3.12/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/coutinho/miniconda/envs/ward-py312/lib/python3.12/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/coutinho/miniconda/envs/ward-py312/lib/python3.12/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/coutinho/miniconda/envs/ward-py312/lib/python3.12/site-packages/click/decorators.py", line 33, in new_func
    return f(get_current_context(), *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/coutinho/miniconda/envs/ward-py312/lib/python3.12/site-packages/ward/_run.py", line 199, in test
    mod_infos = get_info_for_modules(paths, exclude)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/coutinho/miniconda/envs/ward-py312/lib/python3.12/site-packages/ward/_collect.py", line 102, in get_info_for_modules
    if is_test_module(mod) and not _is_excluded_module(mod, exclude):
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/coutinho/miniconda/envs/ward-py312/lib/python3.12/site-packages/ward/_collect.py", line 34, in _is_excluded_module
    return _excluded(_get_module_path(module), exclusions)
                     ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/coutinho/miniconda/envs/ward-py312/lib/python3.12/site-packages/ward/_collect.py", line 30, in _get_module_path
    return Path(module.module_finder.find_module(module.name).path)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'FileFinder' object has no attribute 'find_module'

```

### LINKED ISSUE #374: Python 3.12 Compatibility
I thought it would be worthwhile to have an issue tracking anything needed for Python 3.12 compatibility, as more blockers may come up as some are fixed. So far I can identify two problems:

- [x] #372
- [ ] `distutils` is no longer in stdlib

EDIT: Both of these are now addressed by PR #373.

For the `distutils` migration, it may be as simple as:

```diff
diff --git a/ward/_collect.py b/ward/_collect.py
index d72a57e..d288b10 100644
--- a/ward/_collect.py
+++ b/ward/_collect.py
@@ -5,10 +5,10 @@ import os
 import pkgutil
 import sys
 from dataclasses import dataclass
-from distutils.sysconfig import get_python_lib
 from importlib._bootstrap import ModuleSpec  # type: ignore[import]
 from importlib._bootstrap_external import FileFinder  # type: ignore[import]
 from pathlib import Path
+from sysconfig import get_path
 from types import ModuleType
 from typing import Callable, Iterable, List, Optional, Set, Tuple
 
@@ -113,7 +113,7 @@ def get_info_for_modules(
 
                 # ignore site-packages directories
                 abs_path = dir_path.absolute()
-                if str(abs_path).startswith(get_python_lib()):
+                if str(abs_path).startswith(get_path('platlib')):
                     continue
 
                 # if we have seen this path before, skip it
```

Python 3.12 was released on October 2nd.

@darrenburns I'm not sure how much availability you have for ward maintenance these days, or if there's someone else you can bring in to help, but I'd love to keep using this project with the current Python release and going forward.

### PR DESCRIPTION
**Pull request by taconi**
Closes #372
Closes #374

### CODE REVIEW

**Review by petereon — APPROVED** [review]

**Comment by petereon** [comment]
Well, I tried 😅

**Review by darrenburns — APPROVED** [review]
Thank you 🙏
